# Generated by Django 4.1.1 on 2022-09-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_attemptedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='text',
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='taken_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_questions', to='quiz.takenquiz'),
        ),
    ]
